2024-07-01 15:47:46,304 - utils.logger - INFO - Connected to Redis
2024-07-01 15:48:19,944 - utils.logger - ERROR - Connected to Redis
2024-07-01 15:58:16,050 - utils.logger - INFO - Connected to Redis
2024-07-01 15:58:16,051 - utils.logger - ERROR - Error connecting to Redis: Simulated exception
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\services\redisService.py", line 30, in connect
    raise ValueError("Simulated exception")
ValueError: Simulated exception
2024-07-01 17:17:53,325 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:17:53,327 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:17:53,654 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:17:53,654 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:18:48,622 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:18:48,623 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:18:48,624 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:18:48,624 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:18:50,662 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:18:50,662 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:20:14,331 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:20:14,332 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:20:14,333 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:20:14,333 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:20:16,369 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:20:16,369 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:20:55,053 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:20:55,054 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:20:55,055 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:20:55,055 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:20:57,085 - src.utils.logger - ERROR - Error hmget 'credential:manager:*': 'list' object has no attribute 'items'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 59, in hmget
    itemData = {key.decode('utf-8'): value.decode('utf-8') for key, value in item.items()}
                                                                             ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
2024-07-01 17:20:57,085 - src.utils.logger - ERROR - Error hmget 'credential:manager:*': 'list' object has no attribute 'items'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 59, in hmget
    itemData = {key.decode('utf-8'): value.decode('utf-8') for key, value in item.items()}
                                                                             ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
2024-07-01 17:20:57,092 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:20:57,092 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:23:24,828 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:23:24,829 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:23:24,830 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:23:24,830 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:23:26,860 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:23:26,860 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:23:40,306 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:23:40,307 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:23:40,309 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:23:40,309 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:23:42,344 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:23:42,344 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:23:55,116 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:23:55,118 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:23:55,119 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:23:55,119 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:24:47,678 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:24:47,678 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:25:21,694 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:25:21,695 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:25:21,696 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:25:21,696 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:26:27,790 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:26:27,792 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:26:27,792 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:26:27,792 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:26:31,418 - src.utils.logger - ERROR - Error hmget 'b'example_key'': WRONGTYPE Operation against a key holding the wrong kind of value
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 62, in hmget
    value = self.client.hgetall(key_str)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\commands\core.py", line 4955, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 545, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 546, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 522, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
2024-07-01 17:26:31,418 - src.utils.logger - ERROR - Error hmget 'b'example_key'': WRONGTYPE Operation against a key holding the wrong kind of value
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 62, in hmget
    value = self.client.hgetall(key_str)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\commands\core.py", line 4955, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 545, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 546, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 522, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
2024-07-01 17:26:31,454 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:26:31,454 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:26:49,681 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:26:49,683 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:26:49,684 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:26:49,684 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:27:07,637 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:27:38,693 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:27:38,694 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:27:38,694 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:27:47,095 - src.utils.logger - ERROR - Error hmget 'b'example_key'': WRONGTYPE Operation against a key holding the wrong kind of value
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 62, in hmget
    value = self.client.hgetall(key_str)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\commands\core.py", line 4955, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 545, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 546, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 522, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
2024-07-01 17:27:47,095 - src.utils.logger - ERROR - Error hmget 'b'example_key'': WRONGTYPE Operation against a key holding the wrong kind of value
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 62, in hmget
    value = self.client.hgetall(key_str)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\commands\core.py", line 4955, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 545, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 546, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 522, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
2024-07-01 17:30:43,621 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:30:45,645 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:30:45,647 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:30:45,650 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:30:45,650 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:30:47,677 - src.utils.logger - ERROR - Error hmget 'b'example_key'': WRONGTYPE Operation against a key holding the wrong kind of value
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 63, in hmget
    value = self.client.hgetall(key_str)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\commands\core.py", line 4955, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 545, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 546, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 522, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
2024-07-01 17:30:47,677 - src.utils.logger - ERROR - Error hmget 'b'example_key'': WRONGTYPE Operation against a key holding the wrong kind of value
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 63, in hmget
    value = self.client.hgetall(key_str)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\commands\core.py", line 4955, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 545, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 546, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 522, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\MK\Projects\ServiceApi\myenv\Lib\site-packages\redis\connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
2024-07-01 17:32:03,424 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:32:05,458 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:32:05,460 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:32:05,463 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:32:05,463 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:32:38,766 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:32:40,799 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:32:40,802 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:32:40,805 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:32:40,805 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:36:22,469 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:36:24,488 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:36:24,489 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:36:24,490 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:36:24,490 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:37:28,385 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:37:30,416 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:37:30,418 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:37:30,421 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:37:30,421 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:37:49,073 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:37:51,106 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:37:51,107 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:37:51,110 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:37:51,110 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:39:38,606 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:39:40,641 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:39:40,642 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:39:40,644 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:39:40,644 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:40:04,468 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:40:06,526 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:40:06,528 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:40:06,530 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:40:06,530 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:40:08,553 - src.utils.logger - ERROR - Error hmget 'b'credential:manager:1106'': 'dict' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 64, in hmget
    print(value.decode('utf-8'))
          ^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'decode'
2024-07-01 17:40:08,553 - src.utils.logger - ERROR - Error hmget 'b'credential:manager:1106'': 'dict' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 64, in hmget
    print(value.decode('utf-8'))
          ^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'decode'
2024-07-01 17:40:25,125 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:40:27,143 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:40:27,144 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:40:27,146 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:40:27,146 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:41:11,986 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:41:14,003 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:41:14,004 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:41:14,007 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:41:14,007 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:41:16,019 - src.utils.logger - ERROR - Error hmget 'b'credential:manager:1106'': cannot access local variable 'data' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 64, in hmget
    decoded_data = {key.decode('utf-8'): value.decode('utf-8') for key, value in data.items()}
                                                                                 ^^^^
UnboundLocalError: cannot access local variable 'data' where it is not associated with a value
2024-07-01 17:41:16,019 - src.utils.logger - ERROR - Error hmget 'b'credential:manager:1106'': cannot access local variable 'data' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\redisService.py", line 64, in hmget
    decoded_data = {key.decode('utf-8'): value.decode('utf-8') for key, value in data.items()}
                                                                                 ^^^^
UnboundLocalError: cannot access local variable 'data' where it is not associated with a value
2024-07-01 17:41:37,802 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:41:39,826 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:41:39,828 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:41:39,831 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:41:39,831 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:43:08,986 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:43:11,027 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'Abc@1234'}'
2024-07-01 17:43:11,027 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': 'Abc@1234'}'
2024-07-01 17:43:11,028 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:43:11,030 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:43:11,030 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:43:13,056 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:43:13,056 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 17:45:10,697 - src.utils.logger - INFO - Connected to Redis
2024-07-01 17:45:12,720 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 20:52:02,827 - src.utils.logger - INFO - Connected to Redis
2024-07-01 20:52:04,859 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:44:19,099 - src.utils.logger - INFO - Connected to Redis
2024-07-01 21:44:21,164 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:51:31,823 - src.utils.logger - INFO - Connected to Redis
2024-07-01 21:51:33,863 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:51:33,863 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:52:06,797 - src.utils.logger - INFO - Connected to Redis
2024-07-01 21:52:08,847 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:52:08,847 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:53:30,195 - src.utils.logger - INFO - Connected to Redis
2024-07-01 21:53:32,265 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:53:32,265 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:53:32,269 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:53:32,269 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:53:32,783 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:53:32,783 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:54:06,783 - src.utils.logger - INFO - Connected to Redis
2024-07-01 21:56:13,458 - src.utils.logger - INFO - Connected to Redis
2024-07-01 21:56:15,534 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:56:15,534 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:56:16,041 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:56:16,041 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:56:16,550 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:56:16,550 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:57:31,184 - src.utils.logger - INFO - Connected to Redis
2024-07-01 21:57:33,226 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:57:33,226 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:57:33,738 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:57:33,738 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:57:34,255 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:57:34,255 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:58:39,265 - src.utils.logger - INFO - Connected to Redis
2024-07-01 21:58:41,322 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:58:41,322 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:58:41,840 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:58:41,840 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:58:42,363 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:58:42,363 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:59:35,929 - src.utils.logger - INFO - Connected to Redis
2024-07-01 21:59:37,983 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:59:37,983 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:59:38,493 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:59:38,493 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 21:59:39,011 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 21:59:39,011 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:06:50,672 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 22:08:58,089 - src.utils.logger - ERROR - Failed to connect to MT5 Server
2024-07-01 22:14:48,921 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Manager.ManagerAPI' object has no attribute 'ErrorGetLast'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 28, in connect
    error_code = manager.ErrorGetLast()
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MT5Manager.ManagerAPI' object has no attribute 'ErrorGetLast'
2024-07-01 22:32:00,760 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:32:05,762 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:32:05,762 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:32:19,251 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:32:19,251 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:32:19,773 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:32:19,773 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:33:26,203 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:33:30,630 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-1, <EnMTAPIRetcode.MT_RET_AUTH_ACCOUNT_INVALID: 1001>, 'Invalid account')
2024-07-01 22:33:30,630 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-1, <EnMTAPIRetcode.MT_RET_AUTH_ACCOUNT_INVALID: 1001>, 'Invalid account')
2024-07-01 22:33:35,477 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-1, <EnMTAPIRetcode.MT_RET_AUTH_ACCOUNT_INVALID: 1001>, 'Invalid account')
2024-07-01 22:33:35,477 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-1, <EnMTAPIRetcode.MT_RET_AUTH_ACCOUNT_INVALID: 1001>, 'Invalid account')
2024-07-01 22:33:35,995 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:33:35,995 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:34:32,523 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:34:41,783 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:34:41,783 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:34:59,750 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:37:09,228 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-1, <EnMTAPIRetcode.MT_RET_ERR_NETWORK: 7>, 'Network error')
2024-07-01 22:37:09,228 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-1, <EnMTAPIRetcode.MT_RET_ERR_NETWORK: 7>, 'Network error')
2024-07-01 22:37:09,238 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:37:09,238 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:45:08,537 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:45:10,573 - src.utils.logger - INFO - Redis DB is being flushed
2024-07-01 22:45:10,575 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:45:59,046 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:46:01,068 - src.utils.logger - INFO - Redis DB is being flushed
2024-07-01 22:46:01,071 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:46:13,160 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:46:15,200 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'GuO*Pm5u'}'
2024-07-01 22:46:15,202 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': '2oMkWn-c'}'
2024-07-01 22:46:15,203 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:46:15,204 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:46:15,204 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:46:17,264 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:46:17,264 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:46:17,264 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:46:17,772 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:46:17,772 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:46:17,772 - src.utils.logger - WARNING - Failed to connect to MT5 Server: (-2, <EnMTAPIRetcode.MT_RET_ERROR: 2>, 'Incorrect parameter type')
2024-07-01 22:46:18,279 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:46:18,279 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:46:18,279 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:46:41,869 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:46:43,890 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'GuO*Pm5u'}'
2024-07-01 22:46:43,891 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': '2oMkWn-c'}'
2024-07-01 22:46:43,891 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:46:43,892 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:46:43,892 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:46:46,431 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:46:46,431 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:46:46,431 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:46:46,929 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:46:46,929 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:46:46,929 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:46:46,937 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:46:46,937 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:46:46,937 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:47:17,936 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:47:19,966 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'GuO*Pm5u'}'
2024-07-01 22:47:19,967 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': '2oMkWn-c'}'
2024-07-01 22:47:19,968 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:47:19,970 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:47:19,970 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:47:22,526 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:47:22,526 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:47:22,526 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:47:23,018 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:47:23,018 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:47:23,018 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:47:23,023 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:47:23,023 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:47:23,023 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:50:33,501 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:50:35,535 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'GuO*Pm5u'}'
2024-07-01 22:50:35,536 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': '2oMkWn-c'}'
2024-07-01 22:50:35,536 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:50:35,537 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:50:35,537 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:50:38,075 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:50:38,075 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:50:38,075 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:50:38,605 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:50:38,605 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:50:38,605 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:50:38,611 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:50:38,611 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:50:38,611 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:51:21,608 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:51:23,641 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'GuO*Pm5u'}'
2024-07-01 22:51:23,642 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': '2oMkWn-c'}'
2024-07-01 22:51:23,643 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:51:23,645 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:51:23,645 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:51:26,143 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:51:26,143 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:51:26,143 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:51:26,582 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:51:26,582 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:51:26,582 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:51:26,590 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:51:26,590 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:51:26,590 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:52:41,311 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:52:43,822 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:52:43,822 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:52:44,328 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:52:44,328 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:52:44,331 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:52:44,331 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:53:55,082 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:53:57,111 - src.utils.logger - INFO - Redis DB is being flushed
2024-07-01 22:53:57,575 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:53:57,575 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:53:58,098 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:53:58,098 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:53:58,105 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:53:58,105 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:54:03,337 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:54:05,367 - src.utils.logger - INFO - Redis DB is being flushed
2024-07-01 22:54:05,368 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:54:18,175 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:54:20,221 - src.utils.logger - INFO - Key 'credential:manager:1105' set to '{'login': 1105, 'password': 'GuO*Pm5u'}'
2024-07-01 22:54:20,223 - src.utils.logger - INFO - Key 'credential:manager:1106' set to '{'login': 1106, 'password': '2oMkWn-c'}'
2024-07-01 22:54:20,224 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:54:20,226 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:54:20,226 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:54:22,821 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:54:22,821 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:54:22,821 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:54:23,358 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:54:23,358 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:54:23,358 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:54:23,366 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:54:23,366 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:54:23,366 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:57:45,975 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:57:48,498 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:57:48,498 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:57:48,978 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:57:48,978 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:57:48,997 - src.utils.logger - INFO - Disconnected from MT5 Server
2024-07-01 22:57:48,997 - src.utils.logger - INFO - Disconnected from MT5 Server
2024-07-01 22:57:49,010 - src.utils.logger - INFO - Disconnected from MT5 Server
2024-07-01 22:57:49,010 - src.utils.logger - INFO - Disconnected from MT5 Server
2024-07-01 22:57:49,012 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:57:49,012 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 22:58:27,155 - src.utils.logger - INFO - Connected to Redis
2024-07-01 22:58:50,704 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:58:50,704 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 22:59:23,160 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 22:59:23,160 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:02:15,228 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:02:17,770 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Service' object has no attribute 'connected'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    if not self.connected:  # Assuming connected is a flag indicating first connection
           ^^^^^^^^^^^^^^
AttributeError: 'MT5Service' object has no attribute 'connected'. Did you mean: 'connect'?
2024-07-01 23:02:17,770 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Service' object has no attribute 'connected'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    if not self.connected:  # Assuming connected is a flag indicating first connection
           ^^^^^^^^^^^^^^
AttributeError: 'MT5Service' object has no attribute 'connected'. Did you mean: 'connect'?
2024-07-01 23:02:19,288 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Service' object has no attribute 'connected'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    if not self.connected:  # Assuming connected is a flag indicating first connection
           ^^^^^^^^^^^^^^
AttributeError: 'MT5Service' object has no attribute 'connected'. Did you mean: 'connect'?
2024-07-01 23:02:19,288 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Service' object has no attribute 'connected'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    if not self.connected:  # Assuming connected is a flag indicating first connection
           ^^^^^^^^^^^^^^
AttributeError: 'MT5Service' object has no attribute 'connected'. Did you mean: 'connect'?
2024-07-01 23:02:19,810 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:02:19,810 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:02:47,944 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:02:50,466 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:02:50,466 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:02:50,986 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:02:50,986 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:04:26,201 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:04:33,656 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:04:33,656 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:05:38,585 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:05:45,400 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:05:45,400 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:06:40,397 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:06:46,225 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:06:46,225 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:06:54,262 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:06:59,245 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:06:59,245 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:08:10,573 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:08:17,627 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:08:23,294 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:08:57,407 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:09:07,160 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:09:07,656 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:09:07,660 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:12:00,761 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:12:03,283 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:12:03,789 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:12:03,796 - src.utils.logger - INFO - Disconnected from MT5 Server
2024-07-01 23:12:03,807 - src.utils.logger - INFO - Disconnected from MT5 Server
2024-07-01 23:12:03,808 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:14:04,728 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:14:07,330 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:14:07,333 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Service' object has no attribute 'manager'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 27, in connect
    await self.subscribe_to_updates()
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 54, in subscribe_to_updates
    self.manager.Subscribe(self.manager.UPDATES_DEAL)
    ^^^^^^^^^^^^
AttributeError: 'MT5Service' object has no attribute 'manager'. Did you mean: 'managers'?
2024-07-01 23:14:07,770 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:14:07,770 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Service' object has no attribute 'manager'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 27, in connect
    await self.subscribe_to_updates()
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 54, in subscribe_to_updates
    self.manager.Subscribe(self.manager.UPDATES_DEAL)
    ^^^^^^^^^^^^
AttributeError: 'MT5Service' object has no attribute 'manager'. Did you mean: 'managers'?
2024-07-01 23:14:07,785 - src.utils.logger - INFO - Disconnected from MT5 Server
2024-07-01 23:14:07,795 - src.utils.logger - INFO - Disconnected from MT5 Server
2024-07-01 23:14:07,796 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:19:20,890 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:19:23,478 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:19:23,479 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Service' object has no attribute 'manager'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    await self.subscribe_to_updates(manager)
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 52, in subscribe_to_updates
    self.manager.Subscribe(manager.UPDATES_DEAL)
    ^^^^^^^^^^^^
AttributeError: 'MT5Service' object has no attribute 'manager'
2024-07-01 23:19:24,445 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:19:24,446 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Service' object has no attribute 'manager'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    await self.subscribe_to_updates(manager)
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 52, in subscribe_to_updates
    self.manager.Subscribe(manager.UPDATES_DEAL)
    ^^^^^^^^^^^^
AttributeError: 'MT5Service' object has no attribute 'manager'
2024-07-01 23:19:24,962 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:20:14,662 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:20:17,145 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:20:17,146 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Manager.ManagerAPI' object has no attribute 'UPDATES_DEAL'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    await self.subscribe_to_updates(manager)
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 52, in subscribe_to_updates
    manager.Subscribe(manager.UPDATES_DEAL)
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MT5Manager.ManagerAPI' object has no attribute 'UPDATES_DEAL'
2024-07-01 23:20:18,136 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:20:18,137 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Manager.ManagerAPI' object has no attribute 'UPDATES_DEAL'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    await self.subscribe_to_updates(manager)
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 52, in subscribe_to_updates
    manager.Subscribe(manager.UPDATES_DEAL)
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MT5Manager.ManagerAPI' object has no attribute 'UPDATES_DEAL'
2024-07-01 23:20:18,670 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:20:31,879 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:20:34,360 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:20:34,362 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Manager.ManagerAPI' object has no attribute 'UPDATES_DEAL'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 26, in connect
    await self.subscribe_to_updates(manager)
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 53, in subscribe_to_updates
    manager.Subscribe(manager.UPDATES_DEAL)
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MT5Manager.ManagerAPI' object has no attribute 'UPDATES_DEAL'
2024-07-01 23:20:35,345 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:20:35,345 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Manager.ManagerAPI' object has no attribute 'UPDATES_DEAL'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 26, in connect
    await self.subscribe_to_updates(manager)
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 53, in subscribe_to_updates
    manager.Subscribe(manager.UPDATES_DEAL)
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MT5Manager.ManagerAPI' object has no attribute 'UPDATES_DEAL'
2024-07-01 23:20:35,880 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:28:05,393 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:28:07,898 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:28:07,899 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Manager.ManagerAPI' object has no attribute 'RegisterDealEventHandler'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    manager.RegisterDealEventHandler(self.on_deal_event)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MT5Manager.ManagerAPI' object has no attribute 'RegisterDealEventHandler'
2024-07-01 23:28:08,910 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:28:08,910 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Manager.ManagerAPI' object has no attribute 'RegisterDealEventHandler'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 25, in connect
    manager.RegisterDealEventHandler(self.on_deal_event)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MT5Manager.ManagerAPI' object has no attribute 'RegisterDealEventHandler'
2024-07-01 23:28:09,482 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:28:36,280 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:28:38,762 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:28:38,763 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Manager.ManagerAPI' object has no attribute 'RegisterDealEventHandler'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 26, in connect
    manager.RegisterDealEventHandler(self.on_deal_event)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MT5Manager.ManagerAPI' object has no attribute 'RegisterDealEventHandler'
2024-07-01 23:28:39,790 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:28:39,790 - src.utils.logger - ERROR - Error connecting to MT5 Server : 'MT5Manager.ManagerAPI' object has no attribute 'RegisterDealEventHandler'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\MK\Projects\ServiceApi\src\services\mt5Service.py", line 26, in connect
    manager.RegisterDealEventHandler(self.on_deal_event)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MT5Manager.ManagerAPI' object has no attribute 'RegisterDealEventHandler'
2024-07-01 23:28:40,359 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:37:04,952 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:37:07,497 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:37:08,450 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:37:08,451 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:37:21,765 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:37:24,245 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:37:24,705 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:37:24,710 - src.utils.logger - INFO - Disconnected from Redis
2024-07-01 23:37:59,569 - src.utils.logger - INFO - Connected to Redis
2024-07-01 23:38:02,066 - src.utils.logger - INFO - Connected to MT5 Server by manager 1106
2024-07-01 23:38:02,508 - src.utils.logger - INFO - Connected to MT5 Server by manager 1105
2024-07-01 23:38:02,511 - src.utils.logger - INFO - Disconnected from MT5 Server
2024-07-01 23:38:02,512 - src.utils.logger - INFO - Disconnected from Redis
